#define HALL_PULSE_PIN 4 
#define ENABLE_SERIAL_PIN 5
#define TEST_PIN 6
#define MCP4151_CS_PIN 10
#define MOSI_PIN 11
#define MISO_PIN 12
#define SCK_PIN 13

#define ROUTER_SPEED_CONTROL_PIN A0
#define ROUTER_LOAD_PIN A1
