#define OLED_RESET_PIN 5
#define ENABLE_SERIAL_PIN 4
#define TEST_PIN 6
#define CONTROL_MODE_SELECT_PIN 8
#define MCP4151_CS_PIN 10
#define MOSI_PIN 11
#define MISO_PIN 12
#define SCK_PIN 13

#define SPEED_CONTROL_REMOTE_PIN A0
#define ROUTER_LOAD_PIN A1
#define SPEED_CONTROL_LOCAL_PIN A2
